package com.hdw.bookmarker.feature.home.presentation.model

import androidx.compose.runtime.Composable
import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import com.hdw.bookmarker.core.model.bookmark.BookmarkItem
import com.hdw.bookmarker.core.model.bookmark.SnapshotId
import com.hdw.bookmarker.feature.home.presentation.component.bookmark.export.BookmarkExportAction
import com.hdw.bookmarker.feature.home.presentation.component.preview.BookmarkPreviewPaneState
import com.hdw.bookmarker.feature.home.presentation.component.preview.rememberBookmarkPreviewPaneState

class HomeScreenUiState(
    val previewPaneState: BookmarkPreviewPaneState,
    val showImportOptionDialog: MutableState<Boolean>,
    val showDefaultBrowserDialog: MutableState<Boolean>,
    val showColorPickerDialog: MutableState<Boolean>,
    val pendingColorPickerSnapshotId: MutableState<SnapshotId?>,
    val showAddItemTypeDialog: MutableState<Boolean>,
    val showExportBookmarkMethodDialog: MutableState<Boolean>,
    val pendingBookmarkExportAction: MutableState<BookmarkExportAction?>,
    val showAddFolderDialog: MutableState<Boolean>,
    val showAddBookmarkDialog: MutableState<Boolean>,
    val pendingFolderTitle: MutableState<String>,
    val pendingFolderDescription: MutableState<String>,
    val pendingBookmarkTitle: MutableState<String>,
    val pendingBookmarkUrl: MutableState<String>,
    val pendingBookmarkDescription: MutableState<String>,
    val pendingBookmarkTags: MutableState<String>,
    val addBookmarkToInbox: MutableState<Boolean>,
    val pendingDeleteSnapshotId: MutableState<SnapshotId?>,
    val pendingDeleteSnapshotTitle: MutableState<String>,
    val pendingActionSnapshotId: MutableState<SnapshotId?>,
    val pendingActionSnapshotTitle: MutableState<String>,
    val pendingRenameSnapshotId: MutableState<SnapshotId?>,
    val pendingSnapshotTitle: MutableState<String>,
    val pendingEditBookmarkItemPath: MutableState<List<Int>?>,
    val pendingDeleteBookmarkItemPath: MutableState<List<Int>?>,
    val pendingDeleteBookmarkItem: MutableState<BookmarkItem?>,
    val pendingEditBookmarkItem: MutableState<BookmarkItem?>,
    val pendingEditBookmarkTitle: MutableState<String>,
    val pendingEditBookmarkUrl: MutableState<String>,
    val pendingEditBookmarkTags: MutableState<String>,
    val pendingEditBookmarkDescription: MutableState<String>,
    val pendingMoveBookmarkItem: MutableState<BookmarkItem?>,
    val pendingMoveBookmarkPath: MutableState<List<Int>?>,
    val pendingMoveSourceSnapshotId: MutableState<SnapshotId?>,
    val pendingMoveTargetSnapshotId: MutableState<SnapshotId?>,
    val showMoveBookmarkDialog: MutableState<Boolean>,
    val isSelectingMoveDestination: MutableState<Boolean>,
    val showSearchDialog: MutableState<Boolean>,
    val searchQuery: MutableState<String>,
    val showBookmarkItemActionDialog: MutableState<Boolean>,
    val showEditBookmarkItemDialog: MutableState<Boolean>,
    val copiedBookmarkItem: MutableState<BookmarkItem?>,
    val pendingPasteFolderPath: MutableState<List<Int>?>,
    val showPasteActionDialog: MutableState<Boolean>,
    val showSnapshotActionDialog: MutableState<Boolean>,
)

@Composable
fun rememberHomeScreenUiState(
    previewPaneState: BookmarkPreviewPaneState = rememberBookmarkPreviewPaneState(),
): HomeScreenUiState = remember(previewPaneState) {
    HomeScreenUiState(
        previewPaneState = previewPaneState,
        showImportOptionDialog = mutableStateOf(false),
        showDefaultBrowserDialog = mutableStateOf(false),
        showColorPickerDialog = mutableStateOf(false),
        pendingColorPickerSnapshotId = mutableStateOf(null),
        showAddItemTypeDialog = mutableStateOf(false),
        showExportBookmarkMethodDialog = mutableStateOf(false),
        pendingBookmarkExportAction = mutableStateOf(null),
        showAddFolderDialog = mutableStateOf(false),
        showAddBookmarkDialog = mutableStateOf(false),
        pendingFolderTitle = mutableStateOf(""),
        pendingFolderDescription = mutableStateOf(""),
        pendingBookmarkTitle = mutableStateOf(""),
        pendingBookmarkUrl = mutableStateOf(""),
        pendingBookmarkDescription = mutableStateOf(""),
        pendingBookmarkTags = mutableStateOf(""),
        addBookmarkToInbox = mutableStateOf(false),
        pendingDeleteSnapshotId = mutableStateOf(null),
        pendingDeleteSnapshotTitle = mutableStateOf(""),
        pendingActionSnapshotId = mutableStateOf(null),
        pendingActionSnapshotTitle = mutableStateOf(""),
        pendingRenameSnapshotId = mutableStateOf(null),
        pendingSnapshotTitle = mutableStateOf(""),
        pendingEditBookmarkItemPath = mutableStateOf(null),
        pendingDeleteBookmarkItemPath = mutableStateOf(null),
        pendingDeleteBookmarkItem = mutableStateOf(null),
        pendingEditBookmarkItem = mutableStateOf(null),
        pendingEditBookmarkTitle = mutableStateOf(""),
        pendingEditBookmarkUrl = mutableStateOf(""),
        pendingEditBookmarkTags = mutableStateOf(""),
        pendingEditBookmarkDescription = mutableStateOf(""),
        pendingMoveBookmarkItem = mutableStateOf(null),
        pendingMoveBookmarkPath = mutableStateOf(null),
        pendingMoveSourceSnapshotId = mutableStateOf(null),
        pendingMoveTargetSnapshotId = mutableStateOf(null),
        showMoveBookmarkDialog = mutableStateOf(false),
        isSelectingMoveDestination = mutableStateOf(false),
        showSearchDialog = mutableStateOf(false),
        searchQuery = mutableStateOf(""),
        showBookmarkItemActionDialog = mutableStateOf(false),
        showEditBookmarkItemDialog = mutableStateOf(false),
        copiedBookmarkItem = mutableStateOf(null),
        pendingPasteFolderPath = mutableStateOf(null),
        showPasteActionDialog = mutableStateOf(false),
        showSnapshotActionDialog = mutableStateOf(false),
    )
}
