build:
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true
  exclude:
    - ProjectStatisticsReport
    - ComplexityReport

output-reports:
  active: true

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
